<?php
$cards = array(
    array(
        'word_1' => '(a) capacity',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => 'the production capacity',
        'sentence' => 'Our plants are working at full capacity',
        'level' => 'At Work',
        'number' => '1',
        'word_1_ua' => 'потужність, максимальна здатність',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'виробнича потужність',
        'sentence_ua' => 'Наші заводи працюють на повну потужність',
        'level_ua' => "На роботі",
        'src' => '',
        ),
    array(
        'word_1' => 'a spreadsheet',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => 'To create a spreadsheet',
        'sentence' => 'To enter data on a spreadsheet',
        'level' => 'Workspace',
        'number' => '45',
        'word_1_ua' => 'електронна таблиця/ листок (в екселі)',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'створити електронну таблицю',
        'sentence_ua' => 'ввести дані в електронну таблицю',
        'level_ua' => "Робочий місце",
        'src' => '',
        ),
    array(
        'word_1' => 'valid',
        'word_2' => 'invalid	',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => 'the document is valid for two years',
        'level' => 'Letters & Forms',
        'number' => '78',
        'word_1_ua' => 'дійсний',
        'word_2_ua' => 'недійсний',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Документ дійсний протягом двох років',
        'level_ua' => "Кореспонденція",
        'src' => '',
        ),
    array(
        'word_1' => 'an agreement',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => "We've reached an agreement",
        'sentence' => 'Our agreement was denounced/violated',
        'level' => 'Business Negotiations',
        'number' => '95',
        'word_1_ua' => 'угода',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'Ми досягли угоди',
        'sentence_ua' => 'Наша угода була розірвана',
        'level_ua' => "Ділові переговори",
        'src' => '',
        ),
    array(
        'word_1' => 'a resource',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => 'untapped resources',
        'sentence' => 'We lacked the resources to do the job properly',
        'level' => 'Management',
        'number' => '113',
        'word_1_ua' => 'ресурс',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'невикористані ресурси',
        'sentence_ua' => 'Нам не вистачало ресурсів, щоб належно виконувати роботу',
        'level_ua' => "Менеджмент",
        'src' => '',
        ),
    array(
        'word_1' => 'law',
        'word_2' => 'a lawyer',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => 'a law firm',
        'level' => 'Compliance',
        'number' => '150',
        'word_1_ua' => 'закон',
        'word_2_ua' => 'юрист',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'юридична фірма',
        'level_ua' => "Дотримання норм",
        'src' => '',
        ),
        																									
    array(
        'word_1' => '(a) volume',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => 'the volume of orders',
        'sentence' => 'Imports of consumer goods have risen in volume by 10%',
        'level' => 'Trade',
        'number' => '169',
        'word_1_ua' => "об'єм, кількість",
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'обсяг замовлень',
        'sentence_ua' => "Імпорт споживчих товарів зріс в об'ємі на 10%",
        'level_ua' => "Торгівля",
        'src' => '',
        ),
    array(
        'word_1' => 'a dimension',
        'word_2' => 'dimensional',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => 'dimension of e-commerce',
        'level' => 'Marketing',
        'number' => '205',
        'word_1_ua' => 'вимір',
        'word_2_ua' => 'просторовий',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'вимір електронної комерції',
        'level_ua' => "Маркетинг",
        'src' => '',
        ),
    array(
        'word_1' => 'carriage',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => 'carriage of goods',
        'sentence' => 'carriage by road',
        'level' => 'Logistics',
        'number' => '242',
        'word_1_ua' => 'перевезення',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'перевезення вантажів',
        'sentence_ua' => 'автоперевезення	',
        'level_ua' => "Логістика",
        'src' => '',
        ),
    array(
        'word_1' => 'supply',
        'word_2' => 'demand	',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => 'elasticity of demand',
        'level' => 'The Economy',
        'number' => '308',
        'word_1_ua' => 'пропозиція',
        'word_2_ua' => 'попит',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'еластичність попиту	',
        'level_ua' => "Економіка",
        'src' => '',
        ),
    );
    return $cards;
?>