<?php
$cards = array(
    array(
        'word_1' => 'der Geburtstag',
        'word_2' => 'die Geburtstage',
        'word_3' => '',
        'sentence_0' => 'das Geburtstagkind',
        'sentence' => 'die Geburtstagsparty',
        'level' => 'Familie',
        'number' => '7',
        'word_1_ua' => 'день народження',
        'word_2_ua' => 'мн.',
        'word_3_ua' => '',
        'sentence_0_ua' => 'іменинник',
        'sentence_ua' => 'вечірка з нагоди дня народження',
        'level_ua' => "Сім'я",
        'src' => '7.jpg',
        ),
    array(
        'word_1' => 'sie',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => 'Sie ist nett.',
        'sentence' => '',
        'level' => 'Familie',
        'number' => '37',
        'word_1_ua' => 'вона',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'Вона мила.',
        'sentence_ua' => '',
        'level_ua' => "Сім'я",
        'src' => '37.jpg',
        ),
    array(
        'word_1' => 'der Reis',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => 'Reis mit Gemüse',
        'sentence' => '',
        'level' => 'Ernährung',
        'number' => '144',
        'word_1_ua' => 'рис',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'рис з овочами',
        'sentence_ua' => '',
        'level_ua' => 'Їжа',
        'src' => '144.jpg',
        ),
    array(
        'word_1' => 'die Wand',
        'word_2' => 'die Wände',
        'word_3' => '',
        'sentence_0' => 'Was hängt an der Wand?',
        'sentence' => '',
        'level' => 'Haus',
        'number' => '189',
        'word_1_ua' => 'стіна',
        'word_2_ua' => 'мн.',
        'word_3_ua' => '',
        'sentence_0_ua' => 'Що висить на стіні?',
        'sentence_ua' => '',
        'level_ua' => 'Дім',
        'src' => '189.jpg',
        ),
    array(
        'word_1' => 'blau',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => 'Ich habe blaue Augen.',
        'sentence' => 'dunkelblau',
        'level' => 'Stoffe und Materialien',
        'number' => '229',
        'word_1_ua' => 'блакитний',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'Я маю блакитні очі.',
        'sentence_ua' => 'темно-синій',
        'level_ua' => 'Речовини та матеріали',
        'src' => '229.jpg',
        ),
    array(
        'word_1' => 'rot',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => 'Er hat rote Haare.',
        'sentence' => '',
        'level' => 'Stoffe und Materialien',
        'number' => '241',
        'word_1_ua' => 'червоний, рудий',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'Він має руде волосся.',
        'sentence_ua' => '',
        'level_ua' => 'Речовини та матеріали',
        'src' => '241.jpg',
        ),
    array(
        'word_1' => 'die Nummer',
        'word_2' => 'die Nummern',
        'word_3' => '',
        'sentence_0' => 'die Hausnummer',
        'sentence' => 'die Kontonummer',
        'level' => 'Wissenschaft und Bildung',
        'number' => '277',
        'word_1_ua' => 'номер',
        'word_2_ua' => 'мн.',
        'word_3_ua' => '',
        'sentence_0_ua' => 'номер будинку',
        'sentence_ua' => 'номер рахунку',
        'level_ua' => 'Освіта та наука',
        'src' => '277.jpg',
        ),
    array(
        'word_1' => 'bis',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => 'Bis morgen!',
        'sentence' => 'Bis gleich!',
        'level' => 'Zeit',
        'number' => '320',
        'word_1_ua' => 'до (якогось моменту в часі)',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'До завтра!',
        'sentence_ua' => 'До зустрічі!',
        'level_ua' => 'Час',
        ),
    array(
        'word_1' => 'die Nacht',
        'word_2' => 'die Nächte',
        'word_3' => '',
        'sentence_0' => 'in der Nacht',
        'sentence' => 'nachts',
        'level' => 'Zeit',
        'number' => '352',
        'word_1_ua' => 'ніч',
        'word_2_ua' => 'мн.',
        'word_3_ua' => '',
        'sentence_0_ua' => 'вночі',
        'sentence_ua' => 'ночами',
        'level_ua' => 'Час',
        'src' => '352.jpg',
        ),
    array(
        'word_1' => 'packen',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => 'Wir müssen noch die Koffer packen.',
        'sentence' => '',
        'level' => 'Reisen',
        'number' => '419',
        'word_1_ua' => 'пакувати',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'Нам потрібно ще пакувати валізи.',
        'sentence_ua' => '',
        'level_ua' => 'Подорожі',
        'src' => '419.jpg',
        ),
    );
    return $cards;
?>