<?php
$cards = array(
    array(
        'word_1' => 'banana f',
        'word_2' => 'plátano m',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => 'Las bananas son más dulces que los plátanos',
        'level' => 'Comida',
        'number' => '5',
        'word_1_ua' => 'банан (жовтий, солодкий сорт)',
        'word_2_ua' => 'банан (зелений, менш солодкий)',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Банани одного сорту солодші, ніж банани іншого сорту',
        'level_ua' => "Їжа",
        'src' => '../img/cards-spanish/5.png',
        ),																				
    array(
        'word_1' => 'ir',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => 'Vamos a la universidad',
        'level' => 'Vida Cotidiana',
        'number' => '64',
        'word_1_ua' => 'їхати, іти',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Ми йдемо в університет',
        'level_ua' => "Побут",
        'src' => '../img/cards-spanish/64.png',
        ),																							
    array(
        'word_1' => 'elegir',
        'word_2' => 'optar',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => 'No puede optar entre pantalones o falda',
        'level' => 'Artículos y Servicios',
        'number' => '78',
        'word_1_ua' => 'вибирати',
        'word_2_ua' => 'обирати',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Я не можу вибрати між штанами та спідницею',
        'level_ua' => "Товари та послуги",
        'src' => '../img/cards-spanish/78.png',
        ),																						
    array(
        'word_1' => 'esposo m',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => "",
        'sentence' => 'Su esposo es médico',
        'level' => 'Familia',
        'number' => '92',
        'word_1_ua' => 'чоловік (одружений)',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Її чоловік - лікар',
        'level_ua' => "Сім'я",
        'src' => '../img/cards-spanish/92.png',
        ),																				
    array(
        'word_1' => 'anteojos m pl',
        'word_2' => 'gafas f pl',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => 'Él lleva gafas desde el nacimiento',
        'level' => 'Aspecto Físico',
        'number' => '117',
        'word_1_ua' => 'окуляри',
        'word_2_ua' => 'окуляри (сонцезахисні)',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Він носить окуляри від народження',
        'level_ua' => "Зовнішній вигляд",
        'src' => '../img/cards-spanish/117.png',
        ),																					
    array(
        'word_1' => 'feliz',
        'word_2' => 'infeliz',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => 'Me siento muy feliz',
        'level' => 'Sentimientos',
        'number' => '143',
        'word_1_ua' => 'щасливий',
        'word_2_ua' => 'нещасливий',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Я почуваюся дуже щасливим',
        'level_ua' => "Емоції",
        'src' => '../img/cards-spanish/143.png',
        ),																																													
    array(
        'word_1' => 'mar f m',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => 'La mar está  intranquila hoy',
        'level' => 'Naturaleza',
        'number' => '178',
        'word_1_ua' => "море",
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => "Море сьогодні неспокійне",
        'level_ua' => "Природа",
        'src' => '../img/cards-spanish/178.png',
        ),						 															
    array(
        'word_1' => 'bailar',
        'word_2' => 'baile m',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => '¡Baila, baila morena!',
        'level' => 'Cultura y Arte',
        'number' => '221',
        'word_1_ua' => 'танцювати',
        'word_2_ua' => 'танець',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Танцюй, танцюй, чорноброва!',
        'level_ua' => "Культура та мистецтво",
        'src' => '../img/cards-spanish/221.png',
        ),																				
    array(
        'word_1' => 'reloj m',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => 'Él no lleva reloj',
        'level' => 'Cosas',
        'number' => '307',
        'word_1_ua' => 'годинник',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Він не носить годинник',
        'level_ua' => "Предмети",
        'src' => '../img/cards-spanish/307.png',
        ),																					
    array(
        'word_1' => 'up',
        'word_2' => '',
        'word_3' => '',
        'sentence_0' => '',
        'sentence' => 'Él tiene un negocio en la ciudad',
        'level' => 'Economía',
        'number' => '495',
        'word_1_ua' => 'бізнес',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Він має бізнес у місті',
        'level_ua' => "Економіка",
        'src' => '../img/cards-spanish/495.png',
        ),
    );
    return $cards;
?>