<?php
$cards = array(
    array(
        'word_1' => 'to troubleshoot',
        'tr_1' => '[ˈtrʌbəlˌʃut]',
        'word_2' => 'a troubleshooting',
        'tr_2' => '[ˈtrʌbəlˌʃutɪŋ]',
        'word_3' => '',
        'tr_3' => '',
        'sentence_0' => '',
        'sentence' => 'You can disable this feature to troubleshoot the problem',
        'level' => 'At Work',
        'number' => '35',
        'word_1_ua' => 'діагностувати та усувати неполадки',
        'word_2_ua' => 'діагностика та усунення неполадок',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Ви можете вимкнути функцію, щоб діагностувати проблему',
        'level_ua' => "На роботі",
        'src' => '',
        ),
    array(
        'word_1' => 'application software',
        'tr_1' => '[ˌæplɪˈkeɪʃənˈsɔftˌweər]',
        'word_2' => '',
        'tr_2' => '',
        'word_3' => '',
        'tr_3' => '',
        'sentence_0' => '',
        'sentence' => 'We are proud of our status among application software developers',
        'level' => 'Personal Computer',
        'number' => '62',
        'word_1_ua' => 'прикладне програмне забезпечення',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Ми пишаємося нашим статусом між розробниками прикладних програм',
        'level_ua' => "Персональний комп'ютер",
        'src' => '',
        ),																							
    array(
        'word_1' => 'a gateway',
        'tr_1' => '[ˈɡeɪtweɪ]',
        'word_2' => 'a payment gateway',
        'tr_2' => '[ˈpeɪmənt ˈɡeɪtweɪ]',
        'word_3' => '',
        'tr_3' => '',
        'sentence_0' => '',
        'sentence' => 'To make a transaction via the payment gateway system',
        'level' => 'E-commerce',
        'number' => '128',
        'word_1_ua' => 'шлюз',
        'word_2_ua' => 'платіжий шлюз',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Здійснювати переказ через платіжні шлюзові системи',
        'level_ua' => "Електронна комерція",
        'src' => '',
        ),																						
    array(
        'word_1' => 'file sharing service',
        'tr_1' => '[fɑɪl ʃerɪŋ ˈsɜrvɪs]',
        'word_2' => '',
        'tr_2' => '',
        'word_3' => '',
        'tr_3' => '',
        'sentence_0' => "",
        'sentence' => 'Dropbox is one of the best online file sharing services',
        'level' => 'Interactions',
        'number' => '171',
        'word_1_ua' => 'файлообмінник/сервіс обміну файлами',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Dropbox - один з найкращих онлайн-сервісів обміну файлами',
        'level_ua' => "Взаємодія в інтернеті",
        'src' => '',
        ),																				
    array(
        'word_1' => 'a hub',
        'tr_1' => '[hʌb]',
        'word_2' => 'an active hub',
        'tr_2' => '[ˈæktɪv hʌb]',
        'word_3' => '',
        'tr_3' => '',
        'sentence_0' => '',
        'sentence' => 'Hubs are replaced by network switches',
        'level' => 'Network',
        'number' => '216',
        'word_1_ua' => 'концентратор',
        'word_2_ua' => 'активний концентратор',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Концентратори заміняють на комутатори',
        'level_ua' => "Ком'ютерна мережа",
        'src' => '',
        ),																					
    array(
        'word_1' => 'a system analyst',
        'tr_1' => '[ˈsɪstəm ˈænəlɪst]',
        'word_2' => '',
        'tr_2' => '',
        'word_3' => '',
        'tr_3' => '',
        'sentence_0' => '',
        'sentence' => 'I work as a system analyst',
        'level' => 'Project Management',
        'number' => '258',
        'word_1_ua' => 'системний аналітик',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Я працюю системним аналітиком',
        'level_ua' => "Управління проектами",
        'src' => '',
        ),																																													
    array(
        'word_1' => 'a patch',
        'tr_1' => '[pætʃ]',
        'word_2' => '',
        'tr_2' => '',
        'word_3' => '',
        'tr_3' => '',
        'sentence_0' => '',
        'sentence' => 'Keep current with updates and patches',
        'level' => 'Security',
        'number' => '340',
        'word_1_ua' => "патч (програмна заплата)",
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => "Будь в курсі оновлень та патчів",
        'level_ua' => "Безпека",
        'src' => '',
        ),						 															
    array(
        'word_1' => 'a solid state drive',
        'tr_1' => '[ˈsɑlɪd steɪt drɑɪv]',
        'word_2' => 'SSD',
        'tr_2' => '[ɛs-ɛs-di]',
        'word_3' => '',
        'tr_3' => '',
        'sentence_0' => '',
        'sentence' => '128 GB SSD',
        'level' => 'Computer Systems',
        'number' => '382',
        'word_1_ua' => 'твердотілий накопичувач',
        'word_2_ua' => 'скор.',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => "Твердотілий накопичувач об'ємом 128 ГБ",
        'level_ua' => "Комп'ютерні системи",
        'src' => '',
        ),																				
    array(
        'word_1' => 'a tab',
        'tr_1' => '[tæb]',
        'word_2' => '',
        'tr_2' => '',
        'word_3' => '',
        'tr_3' => '',
        'sentence_0' => 'Open a new tab',
        'sentence' => 'To restore the tab',
        'level' => 'User Operations',
        'number' => '426',
        'word_1_ua' => 'закладка/ вкладка',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => 'Відкрийте нову вкладку',
        'sentence_ua' => 'Відновити вкладку',
        'level_ua' => "Операції користувача",
        'src' => '',
        ),																					
    array(
        'word_1' => 'a visitor map',
        'tr_1' => '[ˈvɪzɪtər mæp]',
        'word_2' => '',
        'tr_2' => '',
        'word_3' => '',
        'tr_3' => '',
        'sentence_0' => '',
        'sentence' => 'A visitor map shows the location of all your visitors',
        'level' => 'Website',
        'number' => '468',
        'word_1_ua' => 'карта відвідувачів',
        'word_2_ua' => '',
        'word_3_ua' => '',
        'sentence_0_ua' => '',
        'sentence_ua' => 'Карта відвідувачів показує розташування всіх ваших відвідувачів',
        'level_ua' => "Веб-сайт",
        'src' => '',
        ),
    );
    return $cards;
?>